meta_product_name: "Peggo"
meta_title: "Peggo | El software en la nube para la administración de propiedad horizontal"
meta_description: "Peggo es un software admnistrativo para admnistradores donde organizar mejor la información ¡Ingresa ya!"
meta_image: "1.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # requ
